#!/usr/bin/env bash
#a script that transfer a file from client to server
FILE_PATH=$1
IP=$2
USER=$3
SSH_KEY_PATH=$4
if [ $# -lt 3 ]; then
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
elif [ "$#" -eq 3 ]
then
    scp -o StrictHostKeyChecking=no $FILE_PATH "$USER@$IP:~/"
else
    scp -o StrictHostKeyChecking=no -i $SSH_KEY_PATH $FILE_PATH "$USER@IP:~/"
fi
