#!/usr/bin/env bash
#script to install nginx and handle 404
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R $USER:$USER /var/www/html
sudo rm /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '24i\ rewrite^/redirect_me https://youtube.com permanent;' /etc/nginx/site-enabled/default
sudo sed -i '25i\ error_page 404 /error_404.html;' /etc/nginx/site-enabled/default
sudo service nginx start
