#!/usr/bin/env bash
#this scripts installs a load balancer
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

#listen to two servers
echo "
  listen load_balancer
  bind *:80
  mode http
  balance roundrobin
  option httpclose
  option forwardfor
  server 10681-web-01 44.200.137.72:80 check
  server 10681-web-02 3.235.79.226:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
