#!/usr/bin/env bash
# creates the file /var/run/myscript.pid
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# deletes the file /var/run/myscript.pid

trap "echo 'I hate the kill command'; rm /var/run/myscript.pid; exit" SIGTERM
trap "rm /var/run/myscript.pid; exit" SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT

pgrep -f 100-process_and_pid_file >> /var/run/myscript.pid
while :
do
	echo "To infinity and beyond";
	sleep 2
done
