#!/usr/bin/env bash
# fizzbuzz

n=1
while [ $n -le 100 ];
do
if [ $((n%15)) = 0 ];
then
	echo "FizzBuzz";
elif [ $((n%5)) = 0 ];
then
	echo "Buzz";
elif [ $((n%3)) = 0 ];
then
	echo "Fizz";
else
	echo "$n";
fi;
	n=$(( n + 1 ));
done
